server.port=10001

server.address=0.0.0.0
server.shutdown=graceful

spring.web.resources.add-mappings=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.application.name=sentinel-demo-spring-webmvc
spring.mvc.servlet.load-on-startup=1
spring.main.banner-mode=off
