spring:
  cloud:
    sentinel:
      # 在启动期间初始化传输客户端，以便应用程序出现在仪表板中
      # 在第一个业务请求到来之前
      eager: true  # 如果为true, initializer 末尾会直接调 InitExecutor.doInit()，不用等第一次请求
      transport:
        dashboard: 127.0.0.1:8678  # → csp.sentinel.dashboard.server
        # 默认 8719 这是dashboard和当前项目通信端口
        # http://127.0.0.1:8720/getRules?type=flow 和 setRules 是 Sentinel 的命令端口能力
        port: 8720                  # → csp.sentinel.api.port
      web-context-unify: true     # 统一上下文
      metric:
        file-single-size: 134217728  # 128MB = 128 × 1024 × 1024,  metrics 单文件上限, 默认50M
  application:
    name: sentinel-demo-spring-cloud  # → csp.sentinel.app.name
  jmx:
    enabled: false
  main:
    allow-circular-references: true
    banner-mode: off
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 1
  lifecycle:
    timeout-per-shutdown-phase: 90s

# Avoid the default 8080 port, which is commonly occupied by Sentinel Dashboard during local study.
server:
  address: 0.0.0.0
  port: 18080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2048 # 启用压缩的最小响应大小（默认值为2048）
    mime-types: application/json,application/javascript
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 200
